<a href="https://colab.research.google.com/github/Kuoz2/An-lisis_y_Predicci-n/blob/main/Clase_28_04_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Ejercicio L1 — Estadísticas sin funciones built-in

Dada la lista: `temperaturas = [23.1, 19.8, 25.4, 17.2, 30.0, 22.5, 18.9, 27.3, 21.1, 24.6]`

**Sin usar** `max()`, `min()`, `sum()`:
1. Calcula el promedio
2. Encuentra el valor máximo y mínimo
3. Cuenta cuántos valores están sobre el promedio
4. Imprime un reporte con los resultados

### 1. Promedio

In [ ]:
temp = [23.1, 19.8, 25.4, 17.2, 30.0, 22.5, 18.9, 27.3, 21.1, 24.6]

# 1. Promedio
def promedio(valores):

    return sum(valores)/len(valores)

promedio(temp)

22.990000000000002

### 2. Maximo y minimo

In [ ]:
# 2. Maximo y minimo
def maximo(valores):
    max_val = valores[0]
    for x in valores:
      if x > max_val:
        max_val = x
    return max_val

def minimo(valores):
    min_val = valores[0]
    for x in valores:
      if x < min_val:
        min_val = x
    return min_val

print(f"Maxima Temp:{maximo(temp)}")
print(f"Minima Temp:{minimo(temp)}")

Maxima Temp:30.0
Minima Temp:17.2

### 3. Valores sobre promedio

In [ ]:
prom_temp = promedio(temp)
def mayor_prom(valores):
  mayor_que = []
  for x in valores:
    if x > prom_temp:
      mayor_que.append(x)
  return mayor_que

mayor_prom(temp)

[23.1, 25.4, 30.0, 27.3, 24.6]

###4. Reporte

In [ ]:
max_temp = maximo(temp)
min_temp = minimo(temp)
valores_sobre_promedio = mayor_prom(temp)

print("--- Reporte de Temperaturas ---")
print(f"1. Promedio de temperaturas: {prom_temp:.2f}")
print(f"2. Temperatura máxima: {max_temp:.2f}")
print(f"   Temperatura mínima: {min_temp:.2f}")
print(f"3. Valores sobre el promedio ({prom_temp:.2f}): {valores_sobre_promedio}")
print("-------------------------------")

--- Reporte de Temperaturas ---
1. Promedio de temperaturas: 22.99
2. Temperatura máxima: 30.00
   Temperatura mínima: 17.20
3. Valores sobre el promedio (22.99): [23.1, 25.4, 30.0, 27.3, 24.6]
-------------------------------

## 🔹 Ejercicio L2 — Manipulación de listas

Dada: `palabras = ["hola", "mundo", "data", "science", "python", "pandas"]`

1. Agrega `"machine"` y `"learning"` al final
2. Inserta `"bootcamp"` en la posición 2
3. Elimina `"mundo"`
4. Ordena la lista alfabéticamente
5. Crea una nueva lista con solo las palabras de más de 4 letras usando list comprehension
6. Imprime la lista final y la lista filtrada

### 1. Agrega "machine" y "learning" al final

In [ ]:
palabras = ["hola", "mundo", "data", "science", "python", "pandas"]
palabras.append("machine")
palabras.append("learning")
print(f"Lista después de agregar: {palabras}")

Lista después de agregar: ['hola', 'mundo', 'data', 'science', 'python', 'pandas', 'machine', 'learning']

### 2. Inserta "bootcamp" en la posición 2

In [ ]:
# palabras[1] = "bootcamp"
# print(f"Lista después de insertar: {palabras}")

palabras.insert(2, "bootcamp")
print(f"Lista después de insertar: {palabras}")

Lista después de insertar: ['hola', 'mundo', 'bootcamp', 'data', 'science', 'python', 'pandas', 'machine', 'learning']

### 3. Elimina "mundo"

In [ ]:
palabras.remove("mundo")
print(f"Lista después de eliminar: {palabras}")

Lista después de eliminar: ['hola', 'bootcamp', 'data', 'science', 'python', 'pandas', 'machine', 'learning']

### 4. Ordena la lista alfabéticamente

In [ ]:
palabras.sort()
print(f"Lista ordenada: {palabras}")

Lista ordenada: ['bootcamp', 'data', 'hola', 'learning', 'machine', 'pandas', 'python', 'science']

### 5. Crea una nueva lista con solo las palabras de más de 4 letras usando list comprehension

In [ ]:
palabras_filtradas = [palabra for palabra in palabras if len(palabra) > 4]
print(f"Lista filtrada (palabras de más de 4 letras): {palabras_filtradas}")

Lista filtrada (palabras de más de 4 letras): ['bootcamp', 'learning', 'machine', 'pandas', 'python', 'science']

### 6. Imprime la lista final y la lista filtrada

In [ ]:
print(f"Lista final: {palabras}")
print(f"Lista filtrada: {palabras_filtradas}")

Lista final: ['bootcamp', 'data', 'hola', 'learning', 'machine', 'pandas', 'python', 'science']
Lista filtrada: ['bootcamp', 'learning', 'machine', 'pandas', 'python', 'science']

## Ejercicio C1 — Calculadora de impuestos

En Chile, el impuesto a la renta se calcula por tramos (2024):

| Tramo | Renta mensual | Tasa |
|-------|--------------|------|
| 1 | Hasta $772.000 | 0% |
| 2 | $772.001 - $1.715.000 | 4% |
| 3 | $1.715.001 - $2.858.000 | 8% |
| 4 | $2.858.001 - $3.975.000 | 13.5% |
| 5 | Más de $3.975.000 | 23% |

Escribe un programa que:
1. Pida la renta mensual con `input()`
2. Calcule el impuesto y la renta líquida
3. Muestre un resumen claro con el tramo, tasa, impuesto y líquido

In [ ]:
# 1. Pide la renta mensual con input()
renta_mensual = int(input("Ingrese su renta mensual en CLP: "))

Ingrese su renta mensual en CLP: 30000000

In [ ]:
# 2. Calcule el impuesto y la renta líquida

impuesto = 0
tasa = "0%"
tramo = "1"

if renta_mensual <= 772000:
    impuesto = 0
    tasa = "0%"
    tramo = "1"
elif renta_mensual <= 1715000:
    impuesto = (renta_mensual - 772000) * 0.04
    tasa = "4%"
    tramo = "2"
elif renta_mensual <= 2858000:
    impuesto = (renta_mensual - 1715000) * 0.08 + (1715000 - 772000) * 0.04 # This calculation needs to be precise with accumulated taxes
    tasa = "8%"
    tramo = "3"
elif renta_mensual <= 3975000:
    impuesto = (renta_mensual - 2858000) * 0.135 + (2858000 - 1715000) * 0.08 + (1715000 - 772000) * 0.04
    tasa = "13.5%"
    tramo = "4"
else:
    impuesto = (renta_mensual - 3975000) * 0.23 + (3975000 - 2858000) * 0.135 + (2858000 - 1715000) * 0.08 + (1715000 - 772000) * 0.04
    tasa = "23%"
    tramo = "5"

renta_liquida = renta_mensual - impuesto
renta_liquida

23734295.0

In [ ]:
# 3. Muestra un resumen claro con el tramo, tasa, impuesto y líquido

print("\n--- Resumen Calculadora de Impuestos ---")
print(f"Renta Mensual Bruta: ${renta_mensual:,.0f}")
print(f"Tramo de Impuesto: {tramo}")
print(f"Tasa Aplicada: {tasa}")
print(f"Impuesto Calculado: ${impuesto:,.0f}")
print(f"Renta Líquida: ${renta_liquida:,.0f}")
print("----------------------------------------")

--- Resumen Calculadora de Impuestos ---
Renta Mensual Bruta: $30,000,000
Tramo de Impuesto: 5
Tasa Aplicada: 23%
Impuesto Calculado: $6,265,705
Renta Líquida: $23,734,295
----------------------------------------

## Ejercicio P4 — Funciones + Pandas

Combina lo aprendido hoy: crea funciones que trabajen con DataFrames.

Escribe estas funciones:

1. `tipo_mas_fuerte(df)` — retorna el tipo (`Type 1`) con el mayor `Attack` promedio

2. `buscar_pokemon(df, nombre)` — recibe un nombre (o parte de él), retorna todos los pokémon que coincidan con sus stats completas

3. `comparar_tipos(df, tipo1, tipo2)` — recibe dos tipos y retorna un dict comparando:
   - `HP` promedio de cada tipo
   - `Attack` promedio de cada tipo
   - `Speed` promedio de cada tipo
   - Cuál gana en cada categoría

Prueba cada función.

In [ ]:
# importar df
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Data Science Bootcamp/Datasets/pokemon.csv')
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

### Tipo mas fuerte

In [ ]:
df.groupby("Type 1")['Attack'].mean().sort_values(ascending=False)

Type 1
Dragon      112.125000
Fighting     96.777778
Ground       95.750000
Rock         92.863636
Steel        92.703704
Dark         88.387097
Fire         84.769231
Flying       78.750000
Poison       74.678571
Water        74.151786
Ghost        73.781250
Normal       73.469388
Grass        73.214286
Ice          72.750000
Psychic      71.456140
Bug          70.971014
Electric     69.090909
Fairy        61.529412
Name: Attack, dtype: float64

In [ ]:
def tipo_mas_fuerte(df):
    strongest_type = df.groupby("Type 1")['Attack'].mean().sort_values(ascending=False)
    return strongest_type

tipo_mas_fuerte(df).head(1)

Type 1
Dragon    112.125
Name: Attack, dtype: float64

In [ ]:
def tipo_mas_fuerte(df):
    df_temp = df.copy()
    df_temp['Poder_TCG'] = df_temp['HP'] + df_temp[['Attack', 'Sp. Atk']].max(axis=1)

    tipo_ganador = df_temp.groupby('Type 1')['Poder_TCG'].mean().idxmax()
    return tipo_ganador
    #pass
tipo_mas_fuerte(df)

'Dragon'

### Buscar Pokémon

In [ ]:
def buscar_pokemon(df, nombre):
    return df[df['Name'].str.contains(nombre, case=False, na=False)]

buscar_pokemon(df, 'Char')

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
435,390,Chimchar,Fire,NaN,309,44,58,44,58,44,61,4,False

### Comparar Tipos                        **INCOMPLETO**

In [ ]:
def comparar_tipos(df, tipo1, tipo2):
  a =df[df["Type 1"] == tipo1]
  a =a["HP", "Attack", "Speed"]
  b =df[df["Type 2"] == tipo2]
  print(a)
comparar_tipos(df,"Fire", "Water")

       #                       Name Type 1    Type 2  Total   HP  Attack  \
4      4                 Charmander   Fire       NaN    309   39      52
5      5                 Charmeleon   Fire       NaN    405   58      64
6      6                  Charizard   Fire    Flying    534   78      84
7      6  CharizardMega Charizard X   Fire    Dragon    634   78     130
8      6  CharizardMega Charizard Y   Fire    Flying    634   78     104
42    37                     Vulpix   Fire       NaN    299   38      41
43    38                  Ninetales   Fire       NaN    505   73      76
63    58                  Growlithe   Fire       NaN    350   55      70
64    59                   Arcanine   Fire       NaN    555   90     110
83    77                     Ponyta   Fire       NaN    410   50      85
84    78                   Rapidash   Fire       NaN    500   65     100
135  126                     Magmar   Fire       NaN    495   65      95
147  136                    Flareon   Fire       NaN    525   65     130
158  146                    Moltres   Fire    Flying    580   90     100
169  155                  Cyndaquil   Fire       NaN    309   39      52
170  156                    Quilava   Fire       NaN    405   58      64
171  157                 Typhlosion   Fire       NaN    534   78      84
236  218                     Slugma   Fire       NaN    250   40      40
237  219                   Magcargo   Fire      Rock    410   50      50
259  240                      Magby   Fire       NaN    365   45      75
263  244                      Entei   Fire       NaN    580  115     115
270  250                      Ho-oh   Fire    Flying    680  106     130
276  255                    Torchic   Fire       NaN    310   45      60
277  256                  Combusken   Fire  Fighting    405   60      85
278  257                   Blaziken   Fire  Fighting    530   80     120
279  257      BlazikenMega Blaziken   Fire  Fighting    630   80     160
352  322                      Numel   Fire    Ground    305   60      60
353  323                   Camerupt   Fire    Ground    460   70     100
354  323      CameruptMega Camerupt   Fire    Ground    560   70     120
355  324                    Torkoal   Fire       NaN    470   70      85
435  390                   Chimchar   Fire       NaN    309   44      58
436  391                   Monferno   Fire  Fighting    405   64      78
437  392                  Infernape   Fire  Fighting    534   76     104
518  467                  Magmortar   Fire       NaN    540   75      95
542  485                    Heatran   Fire     Steel    600   91      90
557  498                      Tepig   Fire       NaN    308   65      63
558  499                    Pignite   Fire  Fighting    418   90      93
559  500                     Emboar   Fire  Fighting    528  110     123
572  513                    Pansear   Fire       NaN    316   50      53
573  514                   Simisear   Fire       NaN    498   75      98
614  554                   Darumaka   Fire       NaN    315   70      90
615  555    DarmanitanStandard Mode   Fire       NaN    480  105     140
616  555         DarmanitanZen Mode   Fire   Psychic    540  105      30
692  631                    Heatmor   Fire       NaN    484   85      97
721  653                   Fennekin   Fire       NaN    307   40      45
722  654                    Braixen   Fire       NaN    409   59      59
723  655                    Delphox   Fire   Psychic    534   75      69
730  662                Fletchinder   Fire    Flying    382   62      73
731  663                 Talonflame   Fire    Flying    499   78      81
735  667                     Litleo   Fire    Normal    369   62      50
736  668                     Pyroar   Fire    Normal    507   86      68
799  721                  Volcanion   Fire     Water    600   80     110

     Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary
4         43       60       50     65           1      False
5         58       80       65     80           1      False
6         78      109       85    100           1      False
7        111      130       85    100           1      False
8         78      159      115    100           1      False
42        40       50       65     65           1      False
43        75       81      100    100           1      False
63        45       70       50     60           1      False
64        80      100       80     95           1      False
83        55       65       65     90           1      False
84        70       80       80    105           1      False
135       57      100       85     93           1      False
147       60       95      110     65           1      False
158       90      125       85     90           1       True
169       43       60       50     65           2      False
170       58       80       65     80           2      False
171       78      109       85    100           2      False
236       40       70       40     20           2      False
237      120       80       80     30           2      False
259       37       70       55     83           2      False
263       85       90       75    100           2       True
270       90      110      154     90           2       True
276       40       70       50     45           3      False
277       60       85       60     55           3      False
278       70      110       70     80           3      False
279       80      130       80    100           3      False
352       40       65       45     35           3      False
353       70      105       75     40           3      False
354      100      145      105     20           3      False
355      140       85       70     20           3      False
435       44       58       44     61           4      False
436       52       78       52     81           4      False
437       71      104       71    108           4      False
518       67      125       95     83           4      False
542      106      130      106     77           4       True
557       45       45       45     45           5      False
558       55       70       55     55           5      False
559       65      100       65     65           5      False
572       48       53       48     64           5      False
573       63       98       63    101           5      False
614       45       15       45     50           5      False
615       55       30       55     95           5      False
616      105      140      105     55           5      False
692       66      105       66     65           5      False
721       40       62       60     60           6      False
722       58       90       70     73           6      False
723       72      114      100    104           6      False
730       55       56       52     84           6      False
731       71       74       69    126           6      False
735       58       73       54     72           6      False
736       72      109       66    106           6      False
799      120      130       90     70           6       True