<a href="https://colab.research.google.com/github/Kuoz2/An-lisis_y_Predicci-n/blob/main/pokemon3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Usando el dataset de Pokémon, responde:

1. ¿Cuántos pokémon son legendarios?

2. ¿Cuántos pokémon tienen un `Total` mayor a 500?

3. ¿Cuántos pokémon de tipo Psíquico (`Psychic`) hay en la Generación 1?

4. ¿Cuál es el pokémon más rápido (`Speed`) que NO sea legendario?

5. Lista los 5 tipos con más representantes (`Type 1`)

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/content/drive/MyDrive/CURSOPYTHON/pokemon.csv")

In [4]:
df.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense',
       'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [5]:
legen = df['Legendary'].sum()
legen

np.int64(65)

In [18]:
total_500 = df[df['Total'] > 500].shape[0]
total_500

224

In [10]:
poke_psico= df[(df['Type 1'] == 'Psychic')  & (df['Generation'] == 1)].shape[0]
poke_psico

11

In [11]:
poke_rapid_no_legen = df[df['Legendary'] == False].sort_values("Speed", ascending=False).head(1)
poke_rapid_no_legen

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
315,291,Ninjask,Bug,Flying,456,61,90,45,50,50,160,3,False

In [12]:
top_5_tipos = df['Type 1'].value_counts().head(5)
top_5_tipos

Type 1
Water      112
Normal      98
Grass       70
Bug         69
Psychic     57
Name: count, dtype: int64